steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/vortex-frontend', 
      '-f', 'Vortex Web (Frontend)/Dockerfile', # Указываем путь к файлу
      'Vortex Web (Frontend)/'                  # Указываем папку как контекст сборки
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vortex-frontend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vortex-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vortex-frontend'
      - '--region'
      - 'us-central1' # Проверьте ваш регион!

options:
  logging: CLOUD_LOGGING_ONLY
